#pragma once
#include <vector>
#include <string>
#include "Reading.h"
#include "CPU.h"
#include "Computer.h"
#include <msclr/marshal_cppstd.h>

namespace Project12 {

	using namespace System;
	using namespace System::ComponentModel;
	using namespace System::Collections;
	using namespace System::Windows::Forms;
	using namespace System::Data;
	using namespace System::Drawing;
	using namespace System::Collections::Generic;

	std::vector<std::vector<std::string>>CPUdata;
	std::vector<CPU>CPUs;
	std::vector<std::vector<std::string>>Mobodata;
	std::vector<Motherboard>mobo;
	std::vector<std::vector<std::string>>Coolerdata;
	std::vector<Cooler>Coolers;
	std::vector<std::vector<std::string>>GPUdata;
	std::vector<GPU>gpus;
	std::vector<std::vector<std::string>>PSUdata;
	std::vector<PSU>psu;
	std::vector<std::vector<std::string>>Storagedata;
	std::vector<Storage>storage;
	std::vector<std::vector<std::string>>Ramdata;
	std::vector<Ram>ram;
	std::vector<std::vector<std::string>>Casedata;
	std::vector<Case>cases;
	//

	/// <summary>
	/// Summary for MyForm
	/// </summary>
	public ref class MyForm : public System::Windows::Forms::Form
	{
	public:
		MyForm()
		{
			InitializeComponent();

			ReadCPU(CPUdata, CPUs);
			ReadGPU(GPUdata, gpus);
			ReadCooler(Coolerdata, Coolers);
			ReadPSU(PSUdata, psu);
			ReadRam(Ramdata, ram);
			ReadCase(Casedata, cases);
			ReadStorage(Storagedata, storage);
			ReadMobo(Mobodata, mobo);

			PopulateDataGridView(CPUGrid, CPUdata);
			PopulateDataGridView(GPUGrid, GPUdata);
			PopulateDataGridView(RAMGrid, Ramdata);
			PopulateDataGridView(MotherboardGrid, Mobodata);
			PopulateDataGridView(StorageGrid, Storagedata);
			PopulateDataGridView(CoolerGrid, Coolerdata);
			PopulateDataGridView(PSUGrid, PSUdata);
			PopulateDataGridView(CaseGrid, Casedata);


			
		}

	protected:
		/// <summary>
		/// Clean up any resources being used.
		/// </summary>
		~MyForm()
		{
			if (components)
			{
				delete components;
			}
		}
	//////////////////////////////////////////////////////////////////////////////////////
	/////GUI ELEMENTS : BUTTONS, TABLES, PANELS (AUTOMATICALLY GENERATED BY WINFORMS)/////
	/////////////////////////////////////////////////////////////////////////////////////
	private: System::Windows::Forms::Label^ label1;
	private: System::Windows::Forms::Button^ button1;
	private: System::Windows::Forms::Button^ button2;
	private: System::Windows::Forms::Panel^ panel1;
	private: System::Windows::Forms::Button^ button6;
	private: System::Windows::Forms::Button^ button5;
	private: System::Windows::Forms::Button^ button4;
	private: System::Windows::Forms::Button^ button3;
	private: System::Windows::Forms::Label^ label2;
	private: System::Windows::Forms::Panel^ panel2;
	private: System::Windows::Forms::Button^ button16;
	private: System::Windows::Forms::Button^ button15;
	private: System::Windows::Forms::Button^ button14;

	private: System::Windows::Forms::Button^ button12;
	private: System::Windows::Forms::Button^ button11;
	private: System::Windows::Forms::Button^ button10;
	private: System::Windows::Forms::Button^ button9;
	private: System::Windows::Forms::Button^ button8;
	private: System::Windows::Forms::Button^ button7;
	private: System::Windows::Forms::Label^ label3;
	private: System::Windows::Forms::Panel^ panel3;
	private: System::Windows::Forms::DataGridView^ CPUGrid;

	private: System::Windows::Forms::DataGridViewButtonColumn^ Column1;
	private: System::Windows::Forms::DataGridViewTextBoxColumn^ Column2;
	private: System::Windows::Forms::DataGridViewTextBoxColumn^ Column3;
	private: System::Windows::Forms::DataGridViewTextBoxColumn^ Column4;
	private: System::Windows::Forms::DataGridViewTextBoxColumn^ Column5;
	private: System::Windows::Forms::DataGridViewTextBoxColumn^ Column6;
	private: System::Windows::Forms::Button^ button17;
	private: System::Windows::Forms::Panel^ panel4;
	private: System::Windows::Forms::Button^ button18;
	private: System::Windows::Forms::DataGridView^ GPUGrid;

	private: System::Windows::Forms::DataGridViewTextBoxColumn^ Column7;
	private: System::Windows::Forms::DataGridViewTextBoxColumn^ Column8;
	private: System::Windows::Forms::DataGridViewTextBoxColumn^ Column9;
	private: System::Windows::Forms::DataGridViewTextBoxColumn^ Column10;
	private: System::Windows::Forms::DataGridViewTextBoxColumn^ Column11;
	private: System::Windows::Forms::DataGridViewTextBoxColumn^ Column12;
	private: System::Windows::Forms::Panel^ MotherBoardPanel;
	private: System::Windows::Forms::DataGridView^ MotherboardGrid;

	private: System::Windows::Forms::Button^ button20;
	private: System::Windows::Forms::DataGridViewTextBoxColumn^ Column21;
	private: System::Windows::Forms::DataGridViewTextBoxColumn^ Column22;
	private: System::Windows::Forms::DataGridViewTextBoxColumn^ Column23;
	private: System::Windows::Forms::DataGridViewTextBoxColumn^ Column24;
	private: System::Windows::Forms::DataGridViewTextBoxColumn^ Column25;
	private: System::Windows::Forms::DataGridViewTextBoxColumn^ Column26;
	private: System::Windows::Forms::DataGridViewTextBoxColumn^ Column27;
	private: System::Windows::Forms::Panel^ panel5;
	private: System::Windows::Forms::Button^ button19;
	private: System::Windows::Forms::DataGridView^ RAMGrid;

	private: System::Windows::Forms::DataGridViewTextBoxColumn^ Column13;
	private: System::Windows::Forms::DataGridViewTextBoxColumn^ Column14;
	private: System::Windows::Forms::DataGridViewTextBoxColumn^ Column15;
	private: System::Windows::Forms::DataGridViewTextBoxColumn^ Column16;
	private: System::Windows::Forms::DataGridViewTextBoxColumn^ Column17;
	private: System::Windows::Forms::DataGridViewTextBoxColumn^ Column18;
	private: System::Windows::Forms::DataGridViewTextBoxColumn^ Column19;
	private: System::Windows::Forms::Label^ label4;



	private: System::Windows::Forms::Label^ OutputLabel;
	private: System::Windows::Forms::Panel^ panel6;
	private: System::Windows::Forms::DataGridView^ StorageGrid;

	private: System::Windows::Forms::DataGridViewTextBoxColumn^ Column20;
	private: System::Windows::Forms::DataGridViewTextBoxColumn^ Column28;
	private: System::Windows::Forms::DataGridViewTextBoxColumn^ Column29;
	private: System::Windows::Forms::DataGridViewTextBoxColumn^ Column30;
	private: System::Windows::Forms::DataGridViewTextBoxColumn^ Column31;
	private: System::Windows::Forms::DataGridViewTextBoxColumn^ Column32;
	private: System::Windows::Forms::DataGridViewTextBoxColumn^ Column33;
	private: System::Windows::Forms::Button^ button21;
	private: System::Windows::Forms::Label^ label5;
	private: System::Windows::Forms::Label^ label6;
	private: System::Windows::Forms::Panel^ panel7;
	private: System::Windows::Forms::DataGridView^ CoolerGrid;

	private: System::Windows::Forms::DataGridViewTextBoxColumn^ Column34;
	private: System::Windows::Forms::DataGridViewTextBoxColumn^ Column35;
	private: System::Windows::Forms::DataGridViewTextBoxColumn^ Column36;
	private: System::Windows::Forms::DataGridViewTextBoxColumn^ Column37;
	private: System::Windows::Forms::DataGridViewTextBoxColumn^ Column38;
	private: System::Windows::Forms::DataGridViewTextBoxColumn^ Column39;
	private: System::Windows::Forms::DataGridViewTextBoxColumn^ Column40;
	private: System::Windows::Forms::Button^ button22;
	private: System::Windows::Forms::Panel^ panel8;
	private: System::Windows::Forms::DataGridView^ PSUGrid;

	private: System::Windows::Forms::DataGridViewTextBoxColumn^ Column41;
	private: System::Windows::Forms::DataGridViewTextBoxColumn^ Column42;
	private: System::Windows::Forms::DataGridViewTextBoxColumn^ Column43;
	private: System::Windows::Forms::DataGridViewTextBoxColumn^ Column44;
	private: System::Windows::Forms::DataGridViewTextBoxColumn^ Column45;
	private: System::Windows::Forms::DataGridViewTextBoxColumn^ Column46;
	private: System::Windows::Forms::DataGridViewTextBoxColumn^ Column47;
	private: System::Windows::Forms::Button^ button13;
	private: System::Windows::Forms::Label^ label7;
	private: System::Windows::Forms::Label^ label9;
	private: System::Windows::Forms::Label^ label8;
	private: System::Windows::Forms::Panel^ panel9;
	private: System::Windows::Forms::Button^ button23;
	private: System::Windows::Forms::DataGridView^ CaseGrid;

	private: System::Windows::Forms::DataGridViewTextBoxColumn^ Column48;
	private: System::Windows::Forms::DataGridViewTextBoxColumn^ Column49;
	private: System::Windows::Forms::DataGridViewTextBoxColumn^ Column50;
	private: System::Windows::Forms::DataGridViewTextBoxColumn^ Column51;
	private: System::Windows::Forms::DataGridViewTextBoxColumn^ Column52;
	private: System::Windows::Forms::DataGridViewTextBoxColumn^ Column53;
	private: System::Windows::Forms::Label^ label10;
	private: System::Windows::Forms::Label^ label11;



	
	protected:


	private:
		/// <summary>
		/// Required designer variable.
		/// </summary>
		System::ComponentModel::Container^ components;

///////////////////////////////////////////////////////////////////
///////////CODE GENERATED AUTOMATICALLY BY WINFORMS////////////////
///////////////////////////////////////////////////////////////////
#pragma region Windows Form Designer generated code
		/// <summary>
		/// Required method for Designer support - do not modify
		/// the contents of this method with the code editor.
		/// </summary>
		void InitializeComponent(void)
		{
			this->label1 = (gcnew System::Windows::Forms::Label());
			this->button1 = (gcnew System::Windows::Forms::Button());
			this->button2 = (gcnew System::Windows::Forms::Button());
			this->panel1 = (gcnew System::Windows::Forms::Panel());
			this->button6 = (gcnew System::Windows::Forms::Button());
			this->button5 = (gcnew System::Windows::Forms::Button());
			this->button4 = (gcnew System::Windows::Forms::Button());
			this->button3 = (gcnew System::Windows::Forms::Button());
			this->label2 = (gcnew System::Windows::Forms::Label());
			this->panel2 = (gcnew System::Windows::Forms::Panel());
			this->panel7 = (gcnew System::Windows::Forms::Panel());
			this->label7 = (gcnew System::Windows::Forms::Label());
			this->button22 = (gcnew System::Windows::Forms::Button());
			this->CoolerGrid = (gcnew System::Windows::Forms::DataGridView());
			this->Column34 = (gcnew System::Windows::Forms::DataGridViewTextBoxColumn());
			this->Column35 = (gcnew System::Windows::Forms::DataGridViewTextBoxColumn());
			this->Column36 = (gcnew System::Windows::Forms::DataGridViewTextBoxColumn());
			this->Column37 = (gcnew System::Windows::Forms::DataGridViewTextBoxColumn());
			this->Column38 = (gcnew System::Windows::Forms::DataGridViewTextBoxColumn());
			this->Column39 = (gcnew System::Windows::Forms::DataGridViewTextBoxColumn());
			this->Column40 = (gcnew System::Windows::Forms::DataGridViewTextBoxColumn());
			this->panel6 = (gcnew System::Windows::Forms::Panel());
			this->label5 = (gcnew System::Windows::Forms::Label());
			this->button21 = (gcnew System::Windows::Forms::Button());
			this->StorageGrid = (gcnew System::Windows::Forms::DataGridView());
			this->Column20 = (gcnew System::Windows::Forms::DataGridViewTextBoxColumn());
			this->Column28 = (gcnew System::Windows::Forms::DataGridViewTextBoxColumn());
			this->Column29 = (gcnew System::Windows::Forms::DataGridViewTextBoxColumn());
			this->Column30 = (gcnew System::Windows::Forms::DataGridViewTextBoxColumn());
			this->Column31 = (gcnew System::Windows::Forms::DataGridViewTextBoxColumn());
			this->Column32 = (gcnew System::Windows::Forms::DataGridViewTextBoxColumn());
			this->Column33 = (gcnew System::Windows::Forms::DataGridViewTextBoxColumn());
			this->panel8 = (gcnew System::Windows::Forms::Panel());
			this->label11 = (gcnew System::Windows::Forms::Label());
			this->button13 = (gcnew System::Windows::Forms::Button());
			this->PSUGrid = (gcnew System::Windows::Forms::DataGridView());
			this->Column41 = (gcnew System::Windows::Forms::DataGridViewTextBoxColumn());
			this->Column42 = (gcnew System::Windows::Forms::DataGridViewTextBoxColumn());
			this->Column43 = (gcnew System::Windows::Forms::DataGridViewTextBoxColumn());
			this->Column44 = (gcnew System::Windows::Forms::DataGridViewTextBoxColumn());
			this->Column45 = (gcnew System::Windows::Forms::DataGridViewTextBoxColumn());
			this->Column46 = (gcnew System::Windows::Forms::DataGridViewTextBoxColumn());
			this->Column47 = (gcnew System::Windows::Forms::DataGridViewTextBoxColumn());
			this->panel9 = (gcnew System::Windows::Forms::Panel());
			this->label10 = (gcnew System::Windows::Forms::Label());
			this->button23 = (gcnew System::Windows::Forms::Button());
			this->CaseGrid = (gcnew System::Windows::Forms::DataGridView());
			this->Column48 = (gcnew System::Windows::Forms::DataGridViewTextBoxColumn());
			this->Column49 = (gcnew System::Windows::Forms::DataGridViewTextBoxColumn());
			this->Column50 = (gcnew System::Windows::Forms::DataGridViewTextBoxColumn());
			this->Column51 = (gcnew System::Windows::Forms::DataGridViewTextBoxColumn());
			this->Column52 = (gcnew System::Windows::Forms::DataGridViewTextBoxColumn());
			this->Column53 = (gcnew System::Windows::Forms::DataGridViewTextBoxColumn());
			this->MotherBoardPanel = (gcnew System::Windows::Forms::Panel());
			this->label9 = (gcnew System::Windows::Forms::Label());
			this->button20 = (gcnew System::Windows::Forms::Button());
			this->MotherboardGrid = (gcnew System::Windows::Forms::DataGridView());
			this->Column21 = (gcnew System::Windows::Forms::DataGridViewTextBoxColumn());
			this->Column22 = (gcnew System::Windows::Forms::DataGridViewTextBoxColumn());
			this->Column23 = (gcnew System::Windows::Forms::DataGridViewTextBoxColumn());
			this->Column24 = (gcnew System::Windows::Forms::DataGridViewTextBoxColumn());
			this->Column25 = (gcnew System::Windows::Forms::DataGridViewTextBoxColumn());
			this->Column26 = (gcnew System::Windows::Forms::DataGridViewTextBoxColumn());
			this->Column27 = (gcnew System::Windows::Forms::DataGridViewTextBoxColumn());
			this->panel5 = (gcnew System::Windows::Forms::Panel());
			this->label4 = (gcnew System::Windows::Forms::Label());
			this->button19 = (gcnew System::Windows::Forms::Button());
			this->RAMGrid = (gcnew System::Windows::Forms::DataGridView());
			this->Column13 = (gcnew System::Windows::Forms::DataGridViewTextBoxColumn());
			this->Column14 = (gcnew System::Windows::Forms::DataGridViewTextBoxColumn());
			this->Column15 = (gcnew System::Windows::Forms::DataGridViewTextBoxColumn());
			this->Column16 = (gcnew System::Windows::Forms::DataGridViewTextBoxColumn());
			this->Column17 = (gcnew System::Windows::Forms::DataGridViewTextBoxColumn());
			this->Column18 = (gcnew System::Windows::Forms::DataGridViewTextBoxColumn());
			this->Column19 = (gcnew System::Windows::Forms::DataGridViewTextBoxColumn());
			this->panel4 = (gcnew System::Windows::Forms::Panel());
			this->button18 = (gcnew System::Windows::Forms::Button());
			this->GPUGrid = (gcnew System::Windows::Forms::DataGridView());
			this->Column7 = (gcnew System::Windows::Forms::DataGridViewTextBoxColumn());
			this->Column8 = (gcnew System::Windows::Forms::DataGridViewTextBoxColumn());
			this->Column9 = (gcnew System::Windows::Forms::DataGridViewTextBoxColumn());
			this->Column10 = (gcnew System::Windows::Forms::DataGridViewTextBoxColumn());
			this->Column11 = (gcnew System::Windows::Forms::DataGridViewTextBoxColumn());
			this->Column12 = (gcnew System::Windows::Forms::DataGridViewTextBoxColumn());
			this->label8 = (gcnew System::Windows::Forms::Label());
			this->panel3 = (gcnew System::Windows::Forms::Panel());
			this->label6 = (gcnew System::Windows::Forms::Label());
			this->button17 = (gcnew System::Windows::Forms::Button());
			this->CPUGrid = (gcnew System::Windows::Forms::DataGridView());
			this->Column1 = (gcnew System::Windows::Forms::DataGridViewButtonColumn());
			this->Column2 = (gcnew System::Windows::Forms::DataGridViewTextBoxColumn());
			this->Column3 = (gcnew System::Windows::Forms::DataGridViewTextBoxColumn());
			this->Column4 = (gcnew System::Windows::Forms::DataGridViewTextBoxColumn());
			this->Column5 = (gcnew System::Windows::Forms::DataGridViewTextBoxColumn());
			this->Column6 = (gcnew System::Windows::Forms::DataGridViewTextBoxColumn());
			this->button16 = (gcnew System::Windows::Forms::Button());
			this->button15 = (gcnew System::Windows::Forms::Button());
			this->button14 = (gcnew System::Windows::Forms::Button());
			this->button12 = (gcnew System::Windows::Forms::Button());
			this->button11 = (gcnew System::Windows::Forms::Button());
			this->button10 = (gcnew System::Windows::Forms::Button());
			this->button9 = (gcnew System::Windows::Forms::Button());
			this->button8 = (gcnew System::Windows::Forms::Button());
			this->button7 = (gcnew System::Windows::Forms::Button());
			this->label3 = (gcnew System::Windows::Forms::Label());
			this->panel1->SuspendLayout();
			this->panel2->SuspendLayout();
			this->panel7->SuspendLayout();
			(cli::safe_cast<System::ComponentModel::ISupportInitialize^>(this->CoolerGrid))->BeginInit();
			this->panel6->SuspendLayout();
			(cli::safe_cast<System::ComponentModel::ISupportInitialize^>(this->StorageGrid))->BeginInit();
			this->panel8->SuspendLayout();
			(cli::safe_cast<System::ComponentModel::ISupportInitialize^>(this->PSUGrid))->BeginInit();
			this->panel9->SuspendLayout();
			(cli::safe_cast<System::ComponentModel::ISupportInitialize^>(this->CaseGrid))->BeginInit();
			this->MotherBoardPanel->SuspendLayout();
			(cli::safe_cast<System::ComponentModel::ISupportInitialize^>(this->MotherboardGrid))->BeginInit();
			this->panel5->SuspendLayout();
			(cli::safe_cast<System::ComponentModel::ISupportInitialize^>(this->RAMGrid))->BeginInit();
			this->panel4->SuspendLayout();
			(cli::safe_cast<System::ComponentModel::ISupportInitialize^>(this->GPUGrid))->BeginInit();
			this->panel3->SuspendLayout();
			(cli::safe_cast<System::ComponentModel::ISupportInitialize^>(this->CPUGrid))->BeginInit();
			this->SuspendLayout();
			// 
			// label1
			// 
			this->label1->AutoSize = true;
			this->label1->Location = System::Drawing::Point(394, 68);
			this->label1->Name = L"label1";
			this->label1->Size = System::Drawing::Size(171, 16);
			this->label1->TabIndex = 0;
			this->label1->Text = L"Welcome to PC Part Picker!";
			// 
			// button1
			// 
			this->button1->Location = System::Drawing::Point(428, 129);
			this->button1->Name = L"button1";
			this->button1->Size = System::Drawing::Size(93, 43);
			this->button1->TabIndex = 1;
			this->button1->Text = L"Pre-Builds";
			this->button1->UseVisualStyleBackColor = true;
			this->button1->Click += gcnew System::EventHandler(this, &MyForm::button1_Click);
			// 
			// button2
			// 
			this->button2->Location = System::Drawing::Point(409, 227);
			this->button2->Name = L"button2";
			this->button2->Size = System::Drawing::Size(141, 46);
			this->button2->TabIndex = 2;
			this->button2->Text = L"Make Your Own";
			this->button2->UseVisualStyleBackColor = true;
			this->button2->Click += gcnew System::EventHandler(this, &MyForm::button2_Click);
			// 
			// panel1
			// 
			this->panel1->Controls->Add(this->button6);
			this->panel1->Controls->Add(this->button5);
			this->panel1->Controls->Add(this->button4);
			this->panel1->Controls->Add(this->button3);
			this->panel1->Controls->Add(this->label2);
			this->panel1->Dock = System::Windows::Forms::DockStyle::Fill;
			this->panel1->Location = System::Drawing::Point(0, 0);
			this->panel1->Name = L"panel1";
			this->panel1->Size = System::Drawing::Size(978, 549);
			this->panel1->TabIndex = 3;
			this->panel1->Visible = false;
			// 
			// button6
			// 
			this->button6->Location = System::Drawing::Point(409, 335);
			this->button6->Name = L"button6";
			this->button6->Size = System::Drawing::Size(120, 23);
			this->button6->TabIndex = 4;
			this->button6->Text = L"Go Back";
			this->button6->UseVisualStyleBackColor = true;
			this->button6->Click += gcnew System::EventHandler(this, &MyForm::button6_Click);
			// 
			// button5
			// 
			this->button5->Location = System::Drawing::Point(426, 175);
			this->button5->Name = L"button5";
			this->button5->Size = System::Drawing::Size(87, 48);
			this->button5->TabIndex = 3;
			this->button5->Text = L"Editing";
			this->button5->UseVisualStyleBackColor = true;
			// 
			// button4
			// 
			this->button4->Location = System::Drawing::Point(426, 255);
			this->button4->Name = L"button4";
			this->button4->Size = System::Drawing::Size(87, 48);
			this->button4->TabIndex = 2;
			this->button4->Text = L"Office";
			this->button4->UseVisualStyleBackColor = true;
			// 
			// button3
			// 
			this->button3->Location = System::Drawing::Point(426, 92);
			this->button3->Name = L"button3";
			this->button3->Size = System::Drawing::Size(87, 48);
			this->button3->TabIndex = 1;
			this->button3->Text = L"Gaming";
			this->button3->UseVisualStyleBackColor = true;
			// 
			// label2
			// 
			this->label2->AutoSize = true;
			this->label2->Location = System::Drawing::Point(406, 40);
			this->label2->Name = L"label2";
			this->label2->Size = System::Drawing::Size(141, 16);
			this->label2->TabIndex = 0;
			this->label2->Text = L"Choose your Pre-Build";
			// 
			// panel2
			// 
			this->panel2->Controls->Add(this->panel9);
			this->panel2->Controls->Add(this->panel8);
			this->panel2->Controls->Add(this->panel7);
			this->panel2->Controls->Add(this->panel6);
			this->panel2->Controls->Add(this->MotherBoardPanel);
			this->panel2->Controls->Add(this->panel5);
			this->panel2->Controls->Add(this->panel4);
			this->panel2->Controls->Add(this->panel3);
			this->panel2->Controls->Add(this->button16);
			this->panel2->Controls->Add(this->button15);
			this->panel2->Controls->Add(this->button14);
			this->panel2->Controls->Add(this->button12);
			this->panel2->Controls->Add(this->button11);
			this->panel2->Controls->Add(this->button10);
			this->panel2->Controls->Add(this->button9);
			this->panel2->Controls->Add(this->button8);
			this->panel2->Controls->Add(this->button7);
			this->panel2->Controls->Add(this->label3);
			this->panel2->Dock = System::Windows::Forms::DockStyle::Fill;
			this->panel2->Location = System::Drawing::Point(0, 0);
			this->panel2->Name = L"panel2";
			this->panel2->Size = System::Drawing::Size(978, 549);
			this->panel2->TabIndex = 4;
			this->panel2->Visible = false;
			// 
			// panel7
			// 
			this->panel7->Controls->Add(this->label7);
			this->panel7->Controls->Add(this->button22);
			this->panel7->Controls->Add(this->CoolerGrid);
			this->panel7->Dock = System::Windows::Forms::DockStyle::Fill;
			this->panel7->Location = System::Drawing::Point(0, 0);
			this->panel7->Name = L"panel7";
			this->panel7->Size = System::Drawing::Size(978, 549);
			this->panel7->TabIndex = 16;
			this->panel7->Visible = false;
			// 
			// label7
			// 
			this->label7->AutoSize = true;
			this->label7->Location = System::Drawing::Point(446, 20);
			this->label7->Name = L"label7";
			this->label7->Size = System::Drawing::Size(47, 16);
			this->label7->TabIndex = 2;
			this->label7->Text = L"Cooler";
			// 
			// button22
			// 
			this->button22->Location = System::Drawing::Point(10, 15);
			this->button22->Name = L"button22";
			this->button22->Size = System::Drawing::Size(90, 26);
			this->button22->TabIndex = 1;
			this->button22->Text = L"Go Back";
			this->button22->UseVisualStyleBackColor = true;
			this->button22->Click += gcnew System::EventHandler(this, &MyForm::button22_Click);
			// 
			// CoolerGrid
			// 
			this->CoolerGrid->AutoSizeColumnsMode = System::Windows::Forms::DataGridViewAutoSizeColumnsMode::Fill;
			this->CoolerGrid->BackgroundColor = System::Drawing::Color::Pink;
			this->CoolerGrid->ColumnHeadersHeightSizeMode = System::Windows::Forms::DataGridViewColumnHeadersHeightSizeMode::AutoSize;
			this->CoolerGrid->Columns->AddRange(gcnew cli::array< System::Windows::Forms::DataGridViewColumn^  >(7) {
				this->Column34,
					this->Column35, this->Column36, this->Column37, this->Column38, this->Column39, this->Column40
			});
			this->CoolerGrid->Location = System::Drawing::Point(3, 59);
			this->CoolerGrid->Name = L"CoolerGrid";
			this->CoolerGrid->RowHeadersWidth = 51;
			this->CoolerGrid->RowTemplate->Height = 24;
			this->CoolerGrid->Size = System::Drawing::Size(1000, 400);
			this->CoolerGrid->TabIndex = 0;
			// 
			// Column34
			// 
			this->Column34->HeaderText = L"Name";
			this->Column34->MinimumWidth = 6;
			this->Column34->Name = L"Column34";
			this->Column34->ReadOnly = true;
			// 
			// Column35
			// 
			this->Column35->HeaderText = L"Price";
			this->Column35->MinimumWidth = 6;
			this->Column35->Name = L"Column35";
			this->Column35->ReadOnly = true;
			// 
			// Column36
			// 
			this->Column36->HeaderText = L"RPM";
			this->Column36->MinimumWidth = 6;
			this->Column36->Name = L"Column36";
			this->Column36->ReadOnly = true;
			// 
			// Column37
			// 
			this->Column37->HeaderText = L"Noise";
			this->Column37->MinimumWidth = 6;
			this->Column37->Name = L"Column37";
			this->Column37->ReadOnly = true;
			// 
			// Column38
			// 
			this->Column38->HeaderText = L"Colour";
			this->Column38->MinimumWidth = 6;
			this->Column38->Name = L"Column38";
			this->Column38->ReadOnly = true;
			// 
			// Column39
			// 
			this->Column39->HeaderText = L"AIO";
			this->Column39->MinimumWidth = 6;
			this->Column39->Name = L"Column39";
			this->Column39->ReadOnly = true;
			// 
			// Column40
			// 
			this->Column40->HeaderText = L"Size";
			this->Column40->MinimumWidth = 6;
			this->Column40->Name = L"Column40";
			this->Column40->ReadOnly = true;
			// 
			// panel6
			// 
			this->panel6->Controls->Add(this->label5);
			this->panel6->Controls->Add(this->button21);
			this->panel6->Controls->Add(this->StorageGrid);
			this->panel6->Dock = System::Windows::Forms::DockStyle::Fill;
			this->panel6->Location = System::Drawing::Point(0, 0);
			this->panel6->Name = L"panel6";
			this->panel6->Size = System::Drawing::Size(978, 549);
			this->panel6->TabIndex = 15;
			this->panel6->Visible = false;
			// 
			// label5
			// 
			this->label5->AutoSize = true;
			this->label5->Location = System::Drawing::Point(435, 17);
			this->label5->Name = L"label5";
			this->label5->Size = System::Drawing::Size(55, 16);
			this->label5->TabIndex = 2;
			this->label5->Text = L"Storage";
			// 
			// button21
			// 
			this->button21->Location = System::Drawing::Point(12, 12);
			this->button21->Name = L"button21";
			this->button21->Size = System::Drawing::Size(163, 27);
			this->button21->TabIndex = 1;
			this->button21->Text = L"Go Back";
			this->button21->UseVisualStyleBackColor = true;
			this->button21->Click += gcnew System::EventHandler(this, &MyForm::button21_Click);
			// 
			// StorageGrid
			// 
			this->StorageGrid->AllowUserToAddRows = false;
			this->StorageGrid->AllowUserToDeleteRows = false;
			this->StorageGrid->AllowUserToResizeColumns = false;
			this->StorageGrid->AllowUserToResizeRows = false;
			this->StorageGrid->Anchor = static_cast<System::Windows::Forms::AnchorStyles>(((System::Windows::Forms::AnchorStyles::Top | System::Windows::Forms::AnchorStyles::Left)
				| System::Windows::Forms::AnchorStyles::Right));
			this->StorageGrid->AutoSizeColumnsMode = System::Windows::Forms::DataGridViewAutoSizeColumnsMode::Fill;
			this->StorageGrid->BackgroundColor = System::Drawing::Color::Thistle;
			this->StorageGrid->ColumnHeadersHeightSizeMode = System::Windows::Forms::DataGridViewColumnHeadersHeightSizeMode::AutoSize;
			this->StorageGrid->Columns->AddRange(gcnew cli::array< System::Windows::Forms::DataGridViewColumn^  >(7) {
				this->Column20,
					this->Column28, this->Column29, this->Column30, this->Column31, this->Column32, this->Column33
			});
			this->StorageGrid->EditMode = System::Windows::Forms::DataGridViewEditMode::EditOnEnter;
			this->StorageGrid->Location = System::Drawing::Point(0, 45);
			this->StorageGrid->Name = L"StorageGrid";
			this->StorageGrid->RowHeadersWidth = 51;
			this->StorageGrid->RowTemplate->Height = 24;
			this->StorageGrid->Size = System::Drawing::Size(1000, 400);
			this->StorageGrid->TabIndex = 0;
			// 
			// Column20
			// 
			this->Column20->HeaderText = L"Name";
			this->Column20->MinimumWidth = 6;
			this->Column20->Name = L"Column20";
			this->Column20->ReadOnly = true;
			// 
			// Column28
			// 
			this->Column28->HeaderText = L"Price";
			this->Column28->MinimumWidth = 6;
			this->Column28->Name = L"Column28";
			this->Column28->ReadOnly = true;
			// 
			// Column29
			// 
			this->Column29->HeaderText = L"Capacity";
			this->Column29->MinimumWidth = 6;
			this->Column29->Name = L"Column29";
			this->Column29->ReadOnly = true;
			// 
			// Column30
			// 
			this->Column30->HeaderText = L"Price per Gigabyte";
			this->Column30->MinimumWidth = 6;
			this->Column30->Name = L"Column30";
			this->Column30->ReadOnly = true;
			// 
			// Column31
			// 
			this->Column31->HeaderText = L"Cache";
			this->Column31->MinimumWidth = 6;
			this->Column31->Name = L"Column31";
			this->Column31->ReadOnly = true;
			// 
			// Column32
			// 
			this->Column32->HeaderText = L"Form";
			this->Column32->MinimumWidth = 6;
			this->Column32->Name = L"Column32";
			this->Column32->ReadOnly = true;
			// 
			// Column33
			// 
			this->Column33->HeaderText = L"Interface";
			this->Column33->MinimumWidth = 6;
			this->Column33->Name = L"Column33";
			this->Column33->ReadOnly = true;
			// 
			// panel8
			// 
			this->panel8->Controls->Add(this->label11);
			this->panel8->Controls->Add(this->button13);
			this->panel8->Controls->Add(this->PSUGrid);
			this->panel8->Dock = System::Windows::Forms::DockStyle::Fill;
			this->panel8->Location = System::Drawing::Point(0, 0);
			this->panel8->Name = L"panel8";
			this->panel8->Size = System::Drawing::Size(978, 549);
			this->panel8->TabIndex = 17;
			this->panel8->Visible = false;
			// 
			// label11
			// 
			this->label11->AutoSize = true;
			this->label11->Location = System::Drawing::Point(406, 20);
			this->label11->Name = L"label11";
			this->label11->Size = System::Drawing::Size(35, 16);
			this->label11->TabIndex = 2;
			this->label11->Text = L"PSU";
			// 
			// button13
			// 
			this->button13->Location = System::Drawing::Point(15, 15);
			this->button13->Name = L"button13";
			this->button13->Size = System::Drawing::Size(109, 26);
			this->button13->TabIndex = 1;
			this->button13->Text = L"Go Back";
			this->button13->UseVisualStyleBackColor = true;
			this->button13->Click += gcnew System::EventHandler(this, &MyForm::button13_Click);
			// 
			// PSUGrid
			// 
			this->PSUGrid->AutoSizeColumnsMode = System::Windows::Forms::DataGridViewAutoSizeColumnsMode::Fill;
			this->PSUGrid->BackgroundColor = System::Drawing::Color::MediumSlateBlue;
			this->PSUGrid->ColumnHeadersHeightSizeMode = System::Windows::Forms::DataGridViewColumnHeadersHeightSizeMode::AutoSize;
			this->PSUGrid->Columns->AddRange(gcnew cli::array< System::Windows::Forms::DataGridViewColumn^  >(7) {
				this->Column41, this->Column42,
					this->Column43, this->Column44, this->Column45, this->Column46, this->Column47
			});
			this->PSUGrid->Location = System::Drawing::Point(0, 47);
			this->PSUGrid->Name = L"PSUGrid";
			this->PSUGrid->RowHeadersWidth = 51;
			this->PSUGrid->RowTemplate->Height = 24;
			this->PSUGrid->Size = System::Drawing::Size(1000, 400);
			this->PSUGrid->TabIndex = 0;
			// 
			// Column41
			// 
			this->Column41->HeaderText = L"Name";
			this->Column41->MinimumWidth = 6;
			this->Column41->Name = L"Column41";
			this->Column41->ReadOnly = true;
			// 
			// Column42
			// 
			this->Column42->HeaderText = L"Price";
			this->Column42->MinimumWidth = 6;
			this->Column42->Name = L"Column42";
			this->Column42->ReadOnly = true;
			// 
			// Column43
			// 
			this->Column43->HeaderText = L"Size";
			this->Column43->MinimumWidth = 6;
			this->Column43->Name = L"Column43";
			this->Column43->ReadOnly = true;
			// 
			// Column44
			// 
			this->Column44->HeaderText = L"Rating";
			this->Column44->MinimumWidth = 6;
			this->Column44->Name = L"Column44";
			this->Column44->ReadOnly = true;
			// 
			// Column45
			// 
			this->Column45->HeaderText = L"Wattage";
			this->Column45->MinimumWidth = 6;
			this->Column45->Name = L"Column45";
			this->Column45->ReadOnly = true;
			// 
			// Column46
			// 
			this->Column46->HeaderText = L"Modular";
			this->Column46->MinimumWidth = 6;
			this->Column46->Name = L"Column46";
			this->Column46->ReadOnly = true;
			// 
			// Column47
			// 
			this->Column47->HeaderText = L"Colour";
			this->Column47->MinimumWidth = 6;
			this->Column47->Name = L"Column47";
			this->Column47->ReadOnly = true;
			// 
			// panel9
			// 
			this->panel9->Controls->Add(this->label10);
			this->panel9->Controls->Add(this->button23);
			this->panel9->Controls->Add(this->CaseGrid);
			this->panel9->Dock = System::Windows::Forms::DockStyle::Fill;
			this->panel9->Location = System::Drawing::Point(0, 0);
			this->panel9->Name = L"panel9";
			this->panel9->Size = System::Drawing::Size(978, 549);
			this->panel9->TabIndex = 18;
			this->panel9->Visible = false;
			// 
			// label10
			// 
			this->label10->AutoSize = true;
			this->label10->Location = System::Drawing::Point(425, 18);
			this->label10->Name = L"label10";
			this->label10->Size = System::Drawing::Size(39, 16);
			this->label10->TabIndex = 2;
			this->label10->Text = L"Case";
			// 
			// button23
			// 
			this->button23->Location = System::Drawing::Point(12, 5);
			this->button23->Name = L"button23";
			this->button23->Size = System::Drawing::Size(93, 31);
			this->button23->TabIndex = 1;
			this->button23->Text = L"Go Back";
			this->button23->UseVisualStyleBackColor = true;
			this->button23->Click += gcnew System::EventHandler(this, &MyForm::button23_Click);
			// 
			// CaseGrid
			// 
			this->CaseGrid->Anchor = static_cast<System::Windows::Forms::AnchorStyles>(((System::Windows::Forms::AnchorStyles::Top | System::Windows::Forms::AnchorStyles::Left)
				| System::Windows::Forms::AnchorStyles::Right));
			this->CaseGrid->AutoSizeColumnsMode = System::Windows::Forms::DataGridViewAutoSizeColumnsMode::Fill;
			this->CaseGrid->BackgroundColor = System::Drawing::Color::Indigo;
			this->CaseGrid->ColumnHeadersHeightSizeMode = System::Windows::Forms::DataGridViewColumnHeadersHeightSizeMode::AutoSize;
			this->CaseGrid->Columns->AddRange(gcnew cli::array< System::Windows::Forms::DataGridViewColumn^  >(6) {
				this->Column48, this->Column49,
					this->Column50, this->Column51, this->Column52, this->Column53
			});
			this->CaseGrid->Location = System::Drawing::Point(1, 42);
			this->CaseGrid->Name = L"CaseGrid";
			this->CaseGrid->RowHeadersWidth = 51;
			this->CaseGrid->RowTemplate->Height = 24;
			this->CaseGrid->Size = System::Drawing::Size(1000, 400);
			this->CaseGrid->TabIndex = 0;
			// 
			// Column48
			// 
			this->Column48->HeaderText = L"Name";
			this->Column48->MinimumWidth = 6;
			this->Column48->Name = L"Column48";
			this->Column48->ReadOnly = true;
			// 
			// Column49
			// 
			this->Column49->HeaderText = L"Price";
			this->Column49->MinimumWidth = 6;
			this->Column49->Name = L"Column49";
			this->Column49->ReadOnly = true;
			// 
			// Column50
			// 
			this->Column50->HeaderText = L"Size";
			this->Column50->MinimumWidth = 6;
			this->Column50->Name = L"Column50";
			this->Column50->ReadOnly = true;
			// 
			// Column51
			// 
			this->Column51->HeaderText = L"Colour";
			this->Column51->MinimumWidth = 6;
			this->Column51->Name = L"Column51";
			this->Column51->ReadOnly = true;
			// 
			// Column52
			// 
			this->Column52->HeaderText = L"Panel";
			this->Column52->MinimumWidth = 6;
			this->Column52->Name = L"Column52";
			this->Column52->ReadOnly = true;
			// 
			// Column53
			// 
			this->Column53->HeaderText = L"Volume";
			this->Column53->MinimumWidth = 6;
			this->Column53->Name = L"Column53";
			this->Column53->ReadOnly = true;
			// 
			// MotherBoardPanel
			// 
			this->MotherBoardPanel->Controls->Add(this->label9);
			this->MotherBoardPanel->Controls->Add(this->button20);
			this->MotherBoardPanel->Controls->Add(this->MotherboardGrid);
			this->MotherBoardPanel->Dock = System::Windows::Forms::DockStyle::Fill;
			this->MotherBoardPanel->Location = System::Drawing::Point(0, 0);
			this->MotherBoardPanel->Name = L"MotherBoardPanel";
			this->MotherBoardPanel->Size = System::Drawing::Size(978, 549);
			this->MotherBoardPanel->TabIndex = 13;
			this->MotherBoardPanel->Visible = false;
			// 
			// label9
			// 
			this->label9->AutoSize = true;
			this->label9->Location = System::Drawing::Point(406, 20);
			this->label9->Name = L"label9";
			this->label9->Size = System::Drawing::Size(84, 16);
			this->label9->TabIndex = 2;
			this->label9->Text = L"Motherboard";
			// 
			// button20
			// 
			this->button20->Location = System::Drawing::Point(12, 12);
			this->button20->Name = L"button20";
			this->button20->Size = System::Drawing::Size(146, 33);
			this->button20->TabIndex = 1;
			this->button20->Text = L"Go Back";
			this->button20->UseVisualStyleBackColor = true;
			this->button20->Click += gcnew System::EventHandler(this, &MyForm::button20_Click);
			// 
			// MotherboardGrid
			// 
			this->MotherboardGrid->Anchor = static_cast<System::Windows::Forms::AnchorStyles>(((System::Windows::Forms::AnchorStyles::Top | System::Windows::Forms::AnchorStyles::Left)
				| System::Windows::Forms::AnchorStyles::Right));
			this->MotherboardGrid->AutoSizeColumnsMode = System::Windows::Forms::DataGridViewAutoSizeColumnsMode::Fill;
			this->MotherboardGrid->BackgroundColor = System::Drawing::Color::PaleTurquoise;
			this->MotherboardGrid->ColumnHeadersHeightSizeMode = System::Windows::Forms::DataGridViewColumnHeadersHeightSizeMode::AutoSize;
			this->MotherboardGrid->Columns->AddRange(gcnew cli::array< System::Windows::Forms::DataGridViewColumn^  >(7) {
				this->Column21,
					this->Column22, this->Column23, this->Column24, this->Column25, this->Column26, this->Column27
			});
			this->MotherboardGrid->Location = System::Drawing::Point(0, 51);
			this->MotherboardGrid->Name = L"MotherboardGrid";
			this->MotherboardGrid->RowHeadersWidth = 51;
			this->MotherboardGrid->RowTemplate->Height = 24;
			this->MotherboardGrid->Size = System::Drawing::Size(1000, 371);
			this->MotherboardGrid->TabIndex = 0;
			// 
			// Column21
			// 
			this->Column21->HeaderText = L"Name";
			this->Column21->MinimumWidth = 6;
			this->Column21->Name = L"Column21";
			this->Column21->ReadOnly = true;
			// 
			// Column22
			// 
			this->Column22->HeaderText = L"Price";
			this->Column22->MinimumWidth = 6;
			this->Column22->Name = L"Column22";
			this->Column22->ReadOnly = true;
			// 
			// Column23
			// 
			this->Column23->HeaderText = L"Socket";
			this->Column23->MinimumWidth = 6;
			this->Column23->Name = L"Column23";
			this->Column23->ReadOnly = true;
			// 
			// Column24
			// 
			this->Column24->HeaderText = L"Form Factor";
			this->Column24->MinimumWidth = 6;
			this->Column24->Name = L"Column24";
			this->Column24->ReadOnly = true;
			// 
			// Column25
			// 
			this->Column25->HeaderText = L"Chipset";
			this->Column25->MinimumWidth = 6;
			this->Column25->Name = L"Column25";
			this->Column25->ReadOnly = true;
			// 
			// Column26
			// 
			this->Column26->HeaderText = L"Wi-Fi";
			this->Column26->MinimumWidth = 6;
			this->Column26->Name = L"Column26";
			this->Column26->ReadOnly = true;
			// 
			// Column27
			// 
			this->Column27->HeaderText = L"Colour";
			this->Column27->MinimumWidth = 6;
			this->Column27->Name = L"Column27";
			this->Column27->ReadOnly = true;
			// 
			// panel5
			// 
			this->panel5->Controls->Add(this->label4);
			this->panel5->Controls->Add(this->button19);
			this->panel5->Controls->Add(this->RAMGrid);
			this->panel5->Dock = System::Windows::Forms::DockStyle::Fill;
			this->panel5->Location = System::Drawing::Point(0, 0);
			this->panel5->Name = L"panel5";
			this->panel5->Size = System::Drawing::Size(978, 549);
			this->panel5->TabIndex = 14;
			this->panel5->Visible = false;
			// 
			// label4
			// 
			this->label4->AutoSize = true;
			this->label4->Location = System::Drawing::Point(441, 18);
			this->label4->Name = L"label4";
			this->label4->Size = System::Drawing::Size(37, 16);
			this->label4->TabIndex = 2;
			this->label4->Text = L"RAM";
			// 
			// button19
			// 
			this->button19->Location = System::Drawing::Point(12, 11);
			this->button19->Name = L"button19";
			this->button19->Size = System::Drawing::Size(115, 30);
			this->button19->TabIndex = 1;
			this->button19->Text = L"Go Back";
			this->button19->UseVisualStyleBackColor = true;
			this->button19->Click += gcnew System::EventHandler(this, &MyForm::button19_Click);
			// 
			// RAMGrid
			// 
			this->RAMGrid->AutoSizeColumnsMode = System::Windows::Forms::DataGridViewAutoSizeColumnsMode::Fill;
			this->RAMGrid->BackgroundColor = System::Drawing::Color::LightSeaGreen;
			this->RAMGrid->ColumnHeadersHeightSizeMode = System::Windows::Forms::DataGridViewColumnHeadersHeightSizeMode::AutoSize;
			this->RAMGrid->Columns->AddRange(gcnew cli::array< System::Windows::Forms::DataGridViewColumn^  >(7) {
				this->Column13, this->Column14,
					this->Column15, this->Column16, this->Column17, this->Column18, this->Column19
			});
			this->RAMGrid->Location = System::Drawing::Point(3, 57);
			this->RAMGrid->Name = L"RAMGrid";
			this->RAMGrid->RowHeadersWidth = 51;
			this->RAMGrid->RowTemplate->Height = 24;
			this->RAMGrid->Size = System::Drawing::Size(1000, 400);
			this->RAMGrid->TabIndex = 0;
			// 
			// Column13
			// 
			this->Column13->HeaderText = L"Name";
			this->Column13->MinimumWidth = 6;
			this->Column13->Name = L"Column13";
			// 
			// Column14
			// 
			this->Column14->HeaderText = L"Price";
			this->Column14->MinimumWidth = 6;
			this->Column14->Name = L"Column14";
			// 
			// Column15
			// 
			this->Column15->HeaderText = L"Speed";
			this->Column15->MinimumWidth = 6;
			this->Column15->Name = L"Column15";
			// 
			// Column16
			// 
			this->Column16->HeaderText = L"Capacity";
			this->Column16->MinimumWidth = 6;
			this->Column16->Name = L"Column16";
			// 
			// Column17
			// 
			this->Column17->HeaderText = L"Modules";
			this->Column17->MinimumWidth = 6;
			this->Column17->Name = L"Column17";
			// 
			// Column18
			// 
			this->Column18->HeaderText = L"Price per Gigabyte";
			this->Column18->MinimumWidth = 6;
			this->Column18->Name = L"Column18";
			// 
			// Column19
			// 
			this->Column19->HeaderText = L"Colour";
			this->Column19->MinimumWidth = 6;
			this->Column19->Name = L"Column19";
			// 
			// panel4
			// 
			this->panel4->Controls->Add(this->button18);
			this->panel4->Controls->Add(this->GPUGrid);
			this->panel4->Controls->Add(this->label8);
			this->panel4->Dock = System::Windows::Forms::DockStyle::Fill;
			this->panel4->Location = System::Drawing::Point(0, 0);
			this->panel4->Name = L"panel4";
			this->panel4->Size = System::Drawing::Size(978, 549);
			this->panel4->TabIndex = 12;
			this->panel4->Visible = false;
			// 
			// button18
			// 
			this->button18->Location = System::Drawing::Point(12, 12);
			this->button18->Name = L"button18";
			this->button18->Size = System::Drawing::Size(156, 26);
			this->button18->TabIndex = 1;
			this->button18->Text = L"Go Back";
			this->button18->UseVisualStyleBackColor = true;
			this->button18->Click += gcnew System::EventHandler(this, &MyForm::button18_Click);
			// 
			// GPUGrid
			// 
			this->GPUGrid->AutoSizeColumnsMode = System::Windows::Forms::DataGridViewAutoSizeColumnsMode::Fill;
			this->GPUGrid->BackgroundColor = System::Drawing::Color::RosyBrown;
			this->GPUGrid->ColumnHeadersHeightSizeMode = System::Windows::Forms::DataGridViewColumnHeadersHeightSizeMode::AutoSize;
			this->GPUGrid->Columns->AddRange(gcnew cli::array< System::Windows::Forms::DataGridViewColumn^  >(6) {
				this->Column7, this->Column8,
					this->Column9, this->Column10, this->Column11, this->Column12
			});
			this->GPUGrid->Location = System::Drawing::Point(0, 49);
			this->GPUGrid->Name = L"GPUGrid";
			this->GPUGrid->RowHeadersWidth = 51;
			this->GPUGrid->RowTemplate->Height = 24;
			this->GPUGrid->Size = System::Drawing::Size(1000, 400);
			this->GPUGrid->TabIndex = 0;
			// 
			// Column7
			// 
			this->Column7->HeaderText = L"Name";
			this->Column7->MinimumWidth = 6;
			this->Column7->Name = L"Column7";
			this->Column7->ReadOnly = true;
			// 
			// Column8
			// 
			this->Column8->HeaderText = L"Price";
			this->Column8->MinimumWidth = 6;
			this->Column8->Name = L"Column8";
			this->Column8->ReadOnly = true;
			// 
			// Column9
			// 
			this->Column9->HeaderText = L"GPU";
			this->Column9->MinimumWidth = 6;
			this->Column9->Name = L"Column9";
			this->Column9->ReadOnly = true;
			// 
			// Column10
			// 
			this->Column10->HeaderText = L"Clock Speed";
			this->Column10->MinimumWidth = 6;
			this->Column10->Name = L"Column10";
			this->Column10->ReadOnly = true;
			// 
			// Column11
			// 
			this->Column11->HeaderText = L"Length";
			this->Column11->MinimumWidth = 6;
			this->Column11->Name = L"Column11";
			// 
			// Column12
			// 
			this->Column12->HeaderText = L"TDP";
			this->Column12->MinimumWidth = 6;
			this->Column12->Name = L"Column12";
			// 
			// label8
			// 
			this->label8->AutoSize = true;
			this->label8->Location = System::Drawing::Point(437, 17);
			this->label8->Name = L"label8";
			this->label8->Size = System::Drawing::Size(36, 16);
			this->label8->TabIndex = 2;
			this->label8->Text = L"GPU";
			// 
			// panel3
			// 
			this->panel3->Controls->Add(this->label6);
			this->panel3->Controls->Add(this->button17);
			this->panel3->Controls->Add(this->CPUGrid);
			this->panel3->Dock = System::Windows::Forms::DockStyle::Fill;
			this->panel3->Location = System::Drawing::Point(0, 0);
			this->panel3->Name = L"panel3";
			this->panel3->Size = System::Drawing::Size(978, 549);
			this->panel3->TabIndex = 11;
			this->panel3->Visible = false;
			// 
			// label6
			// 
			this->label6->AutoSize = true;
			this->label6->Location = System::Drawing::Point(437, 19);
			this->label6->Name = L"label6";
			this->label6->Size = System::Drawing::Size(35, 16);
			this->label6->TabIndex = 2;
			this->label6->Text = L"CPU";
			// 
			// button17
			// 
			this->button17->Location = System::Drawing::Point(13, 19);
			this->button17->Name = L"button17";
			this->button17->Size = System::Drawing::Size(155, 26);
			this->button17->TabIndex = 1;
			this->button17->Text = L"Go Back";
			this->button17->UseVisualStyleBackColor = true;
			this->button17->Click += gcnew System::EventHandler(this, &MyForm::button17_Click);
			// 
			// CPUGrid
			// 
			this->CPUGrid->AllowUserToDeleteRows = false;
			this->CPUGrid->AutoSizeColumnsMode = System::Windows::Forms::DataGridViewAutoSizeColumnsMode::Fill;
			this->CPUGrid->BackgroundColor = System::Drawing::Color::Chocolate;
			this->CPUGrid->CellBorderStyle = System::Windows::Forms::DataGridViewCellBorderStyle::Raised;
			this->CPUGrid->ColumnHeadersHeightSizeMode = System::Windows::Forms::DataGridViewColumnHeadersHeightSizeMode::AutoSize;
			this->CPUGrid->Columns->AddRange(gcnew cli::array< System::Windows::Forms::DataGridViewColumn^  >(6) {
				this->Column1, this->Column2,
					this->Column3, this->Column4, this->Column5, this->Column6
			});
			this->CPUGrid->Location = System::Drawing::Point(0, 51);
			this->CPUGrid->Name = L"CPUGrid";
			this->CPUGrid->RowHeadersWidth = 51;
			this->CPUGrid->RowTemplate->Height = 24;
			this->CPUGrid->Size = System::Drawing::Size(1000, 400);
			this->CPUGrid->TabIndex = 0;
			// 
			// Column1
			// 
			this->Column1->HeaderText = L"Name";
			this->Column1->MinimumWidth = 6;
			this->Column1->Name = L"Column1";
			this->Column1->ReadOnly = true;
			// 
			// Column2
			// 
			this->Column2->HeaderText = L"Price";
			this->Column2->MinimumWidth = 6;
			this->Column2->Name = L"Column2";
			this->Column2->ReadOnly = true;
			// 
			// Column3
			// 
			this->Column3->HeaderText = L"Cores";
			this->Column3->MinimumWidth = 6;
			this->Column3->Name = L"Column3";
			this->Column3->ReadOnly = true;
			// 
			// Column4
			// 
			this->Column4->HeaderText = L"CLock Speed";
			this->Column4->MinimumWidth = 6;
			this->Column4->Name = L"Column4";
			this->Column4->ReadOnly = true;
			// 
			// Column5
			// 
			this->Column5->HeaderText = L"TDP";
			this->Column5->MinimumWidth = 6;
			this->Column5->Name = L"Column5";
			this->Column5->ReadOnly = true;
			// 
			// Column6
			// 
			this->Column6->HeaderText = L"Graphics";
			this->Column6->MinimumWidth = 6;
			this->Column6->Name = L"Column6";
			this->Column6->ReadOnly = true;
			this->Column6->Resizable = System::Windows::Forms::DataGridViewTriState::True;
			// 
			// button16
			// 
			this->button16->Location = System::Drawing::Point(439, 315);
			this->button16->Name = L"button16";
			this->button16->Size = System::Drawing::Size(99, 39);
			this->button16->TabIndex = 10;
			this->button16->Text = L"Go Back";
			this->button16->UseVisualStyleBackColor = true;
			this->button16->Click += gcnew System::EventHandler(this, &MyForm::button16_Click);
			// 
			// button15
			// 
			this->button15->Location = System::Drawing::Point(680, 131);
			this->button15->Name = L"button15";
			this->button15->Size = System::Drawing::Size(99, 39);
			this->button15->TabIndex = 9;
			this->button15->Text = L"Case";
			this->button15->UseVisualStyleBackColor = true;
			this->button15->Click += gcnew System::EventHandler(this, &MyForm::button15_Click);
			// 
			// button14
			// 
			this->button14->Location = System::Drawing::Point(680, 63);
			this->button14->Name = L"button14";
			this->button14->Size = System::Drawing::Size(99, 39);
			this->button14->TabIndex = 8;
			this->button14->Text = L"PSU";
			this->button14->UseVisualStyleBackColor = true;
			this->button14->Click += gcnew System::EventHandler(this, &MyForm::button14_Click);
			// 
			// button12
			// 
			this->button12->Location = System::Drawing::Point(440, 198);
			this->button12->Name = L"button12";
			this->button12->Size = System::Drawing::Size(99, 39);
			this->button12->TabIndex = 6;
			this->button12->Text = L"Cooler";
			this->button12->UseVisualStyleBackColor = true;
			this->button12->Click += gcnew System::EventHandler(this, &MyForm::button12_Click);
			// 
			// button11
			// 
			this->button11->Location = System::Drawing::Point(439, 129);
			this->button11->Name = L"button11";
			this->button11->Size = System::Drawing::Size(99, 39);
			this->button11->TabIndex = 5;
			this->button11->Text = L"Storage";
			this->button11->UseVisualStyleBackColor = true;
			this->button11->Click += gcnew System::EventHandler(this, &MyForm::button11_Click);
			// 
			// button10
			// 
			this->button10->Location = System::Drawing::Point(424, 61);
			this->button10->Name = L"button10";
			this->button10->Size = System::Drawing::Size(127, 39);
			this->button10->TabIndex = 4;
			this->button10->Text = L"Motherboard";
			this->button10->UseVisualStyleBackColor = true;
			this->button10->Click += gcnew System::EventHandler(this, &MyForm::button10_Click);
			// 
			// button9
			// 
			this->button9->Location = System::Drawing::Point(181, 198);
			this->button9->Name = L"button9";
			this->button9->Size = System::Drawing::Size(99, 39);
			this->button9->TabIndex = 3;
			this->button9->Text = L"RAM";
			this->button9->UseVisualStyleBackColor = true;
			this->button9->Click += gcnew System::EventHandler(this, &MyForm::button9_Click);
			// 
			// button8
			// 
			this->button8->Location = System::Drawing::Point(179, 123);
			this->button8->Name = L"button8";
			this->button8->Size = System::Drawing::Size(99, 39);
			this->button8->TabIndex = 2;
			this->button8->Text = L"GPU";
			this->button8->UseVisualStyleBackColor = true;
			this->button8->Click += gcnew System::EventHandler(this, &MyForm::button8_Click);
			// 
			// button7
			// 
			this->button7->Location = System::Drawing::Point(179, 63);
			this->button7->Name = L"button7";
			this->button7->Size = System::Drawing::Size(99, 39);
			this->button7->TabIndex = 1;
			this->button7->Text = L"CPU";
			this->button7->UseVisualStyleBackColor = true;
			this->button7->Click += gcnew System::EventHandler(this, &MyForm::button7_Click);
			// 
			// label3
			// 
			this->label3->AutoSize = true;
			this->label3->Location = System::Drawing::Point(436, 26);
			this->label3->Name = L"label3";
			this->label3->Size = System::Drawing::Size(75, 16);
			this->label3->TabIndex = 0;
			this->label3->Text = L"PC Part List";
			// 
			// MyForm
			// 
			this->AutoScaleDimensions = System::Drawing::SizeF(8, 16);
			this->AutoScaleMode = System::Windows::Forms::AutoScaleMode::Font;
			this->BackColor = System::Drawing::Color::Honeydew;
			this->ClientSize = System::Drawing::Size(978, 549);
			this->Controls->Add(this->panel2);
			this->Controls->Add(this->panel1);
			this->Controls->Add(this->button2);
			this->Controls->Add(this->button1);
			this->Controls->Add(this->label1);
			this->FormBorderStyle = System::Windows::Forms::FormBorderStyle::Fixed3D;
			this->Name = L"MyForm";
			this->Text = L"PC Part Picker";
			this->panel1->ResumeLayout(false);
			this->panel1->PerformLayout();
			this->panel2->ResumeLayout(false);
			this->panel2->PerformLayout();
			this->panel7->ResumeLayout(false);
			this->panel7->PerformLayout();
			(cli::safe_cast<System::ComponentModel::ISupportInitialize^>(this->CoolerGrid))->EndInit();
			this->panel6->ResumeLayout(false);
			this->panel6->PerformLayout();
			(cli::safe_cast<System::ComponentModel::ISupportInitialize^>(this->StorageGrid))->EndInit();
			this->panel8->ResumeLayout(false);
			this->panel8->PerformLayout();
			(cli::safe_cast<System::ComponentModel::ISupportInitialize^>(this->PSUGrid))->EndInit();
			this->panel9->ResumeLayout(false);
			this->panel9->PerformLayout();
			(cli::safe_cast<System::ComponentModel::ISupportInitialize^>(this->CaseGrid))->EndInit();
			this->MotherBoardPanel->ResumeLayout(false);
			this->MotherBoardPanel->PerformLayout();
			(cli::safe_cast<System::ComponentModel::ISupportInitialize^>(this->MotherboardGrid))->EndInit();
			this->panel5->ResumeLayout(false);
			this->panel5->PerformLayout();
			(cli::safe_cast<System::ComponentModel::ISupportInitialize^>(this->RAMGrid))->EndInit();
			this->panel4->ResumeLayout(false);
			this->panel4->PerformLayout();
			(cli::safe_cast<System::ComponentModel::ISupportInitialize^>(this->GPUGrid))->EndInit();
			this->panel3->ResumeLayout(false);
			this->panel3->PerformLayout();
			(cli::safe_cast<System::ComponentModel::ISupportInitialize^>(this->CPUGrid))->EndInit();
			this->ResumeLayout(false);
			this->PerformLayout();
		}
#pragma endregion
	private: System::Void button1_Click(System::Object^ sender, System::EventArgs^ e) {
		panel1->Show();
	}
	private: System::Void button6_Click(System::Object^ sender, System::EventArgs^ e) {
		panel1->Hide();
	}


	private: System::Void button2_Click(System::Object^ sender, System::EventArgs^ e) {
		panel2->Show();
	}
	private: System::Void button16_Click(System::Object^ sender, System::EventArgs^ e) {
		panel2->Hide();
	}

	private: System::Void button7_Click(System::Object^ sender, System::EventArgs^ e) {
		panel3->Show();
	}

	private: System::Void button17_Click(System::Object^ sender, System::EventArgs^ e) {
		panel3->Hide();
	}

	private:System::Void PopulateDataGridView(DataGridView^ dataGridView1, std::vector<std::vector<std::string>>Data)
	{
		
		// Clear existing rows if necessary
		dataGridView1->Rows->Clear();

		// Iterate over each vector<string> in vector
		for (int i = 0; i < Data.size(); i++)
		{
			// Create a new DataGridViewRow for each entry in vector
			DataGridViewRow^ row = gcnew DataGridViewRow();
			row->CreateCells(dataGridView1); // Prepare the row to have cells like dataGridView1

			// Now fill in the cells with values from CPUdata
			for (int j = 0; j < Data[i].size() && j < row->Cells->Count; j++)
			{
				// Add the data to each cell
				row->Cells[j]->Value = gcnew System::String(Data[i][j].c_str());
			}

			// After setting all the cells for the row, add the row to the DataGridView
			dataGridView1->Rows->Add(row);
		}

		// Add data to DataGridView horizontally
	}


	private: System::Void button8_Click(System::Object^ sender, System::EventArgs^ e) {
		panel4->Show();
	}


	private: System::Void button18_Click(System::Object^ sender, System::EventArgs^ e) {
		panel4->Hide();
	}


	private: System::Void button9_Click(System::Object^ sender, System::EventArgs^ e) {
		panel5->Show();

	}
	private: System::Void button19_Click(System::Object^ sender, System::EventArgs^ e) {
		panel5->Hide();

	}


	private: System::Void button10_Click(System::Object^ sender, System::EventArgs^ e) {
		MotherBoardPanel->Show();

	}

	private: System::Void button20_Click(System::Object^ sender, System::EventArgs^ e) {
		MotherBoardPanel->Hide();
	}

	private: System::Void button11_Click(System::Object^ sender, System::EventArgs^ e) {
		panel6->Show();
	}

	private: System::Void button21_Click(System::Object^ sender, System::EventArgs^ e) {
		panel6->Hide();
	}
	private: System::Void button12_Click(System::Object^ sender, System::EventArgs^ e) {
		panel7->Show();
	}
	private: System::Void button22_Click(System::Object^ sender, System::EventArgs^ e) {
		panel7->Hide();
	}
	private: System::Void button14_Click(System::Object^ sender, System::EventArgs^ e) {
		panel8->Show();
	}
	private: System::Void button13_Click(System::Object^ sender, System::EventArgs^ e) {
		panel8->Hide();
	}
	private: System::Void button15_Click(System::Object^ sender, System::EventArgs^ e) {
		panel9->Show();
	}
	private: System::Void button23_Click(System::Object^ sender, System::EventArgs^ e) {
		panel9->Hide();
	}
	};

}
